# Generated by Django 4.0.3 on 2022-03-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mod_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Enter mod name', max_length=250)),
                ('descr_short', models.CharField(max_length=250)),
                ('descr_long', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('game_version', models.FloatField()),
                ('download_count', models.IntegerField()),
                ('mod_icon', models.ImageField(upload_to='icons')),
                ('mod_data', models.FileField(upload_to='mod_data')),
                ('mod_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.author')),
                ('mod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod_category')),
            ],
            options={
                'ordering': ('date_updated',),
            },
        ),
    ]
